In [1]:
import numpy as np
from scipy.optimize import linear_sum_assignment

def oblicz_optymalna_transwersale():
    # Definicja macierzy kosztów (Pracownicy x Zadania)
    cost_matrix = np.array([
        [10, 15, 9],
        [9, 18, 5],
        [6, 14, 3]
    ])
    
    print("Macierz kosztów wejściowych:")
    print(cost_matrix)
    print("-" * 50)
    
    # Wyznaczenie optymalnego przydziału
    row_ind, col_ind = linear_sum_assignment(cost_matrix)
    
    # Wyświetlenie wyników
    print("Optymalny przydział (indeksy wiersz -> kolumna):")
    for r, c in zip(row_ind, col_ind):
        print(f"  Pracownik {r} ---> Zadanie {c} (Koszt: {cost_matrix[r, c]} PLN)")
        
    total_cost = cost_matrix[row_ind, col_ind].sum()
    print("-" * 50)
    print(f"Suma minimalna (koszt całkowity): {total_cost} PLN")

if __name__ == "__main__":
    oblicz_optymalna_transwersale()

Macierz kosztów wejściowych:
[[10 15  9]
 [ 9 18  5]
 [ 6 14  3]]
--------------------------------------------------
Optymalny przydział (indeksy wiersz -> kolumna):
  Pracownik 0 ---> Zadanie 1 (Koszt: 15 PLN)
  Pracownik 1 ---> Zadanie 2 (Koszt: 5 PLN)
  Pracownik 2 ---> Zadanie 0 (Koszt: 6 PLN)
--------------------------------------------------
Suma minimalna (koszt całkowity): 26 PLN


In [2]:
import numpy as np
from scipy.optimize import linear_sum_assignment

def maksymalizacja_zysku():
    # Definicja macierzy zysków (Pracownicy x Projekty)
    profit_matrix = np.array([
        [40, 70, 55],
        [45, 60, 50],
        [30, 80, 65]
    ])
    
    # Przekształcenie: maksymalizacja -> minimalizacja
    cost_matrix = profit_matrix * -1
    
    # Uruchomienie algorytmu na zmodyfikowanej macierzy
    row_ind, col_ind = linear_sum_assignment(cost_matrix)
    
    # Prezentacja wyników z użyciem oryginalnych wartości zysków
    print("Optymalny przydział dla maksymalizacji zysku:")
    for r, c in zip(row_ind, col_ind):
        zysk = profit_matrix[r, c]
        print(f"  Pracownik {r} ---> Projekt {c} | Zysk: {zysk} tys. zl")
        
    max_total_profit = profit_matrix[row_ind, col_ind].sum()
    print("-" * 50)
    print(f"Maksymalny zysk calkowity: {max_total_profit} tys. zl")

if __name__ == "__main__":
    maksymalizacja_zysku()

Optymalny przydział dla maksymalizacji zysku:
  Pracownik 0 ---> Projekt 1 | Zysk: 70 tys. zl
  Pracownik 1 ---> Projekt 0 | Zysk: 45 tys. zl
  Pracownik 2 ---> Projekt 2 | Zysk: 65 tys. zl
--------------------------------------------------
Maksymalny zysk calkowity: 180 tys. zl
