<a href="https://colab.research.google.com/github/pgordin/OptDisc2026/blob/main/Grafy1a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importowanie pakietów

In [1]:
import numpy as np
from random import random, seed

# Funkcje grafowe

In [2]:
def print_matrix(vertices, matrix):
  """
  Wypisuje na ekranie graf podany jako macierz sąsiedztwa
  """
  n = len(matrix)
  if (vertices is None) or (len(vertices) != n):
    vv = range(1, n+1)
  else:
    vv = vertices
  for i in range(n):
    print(vv[i], ':', end='')
    for j in range(n):
      if (matrix[i][j]):
        print(" ", vv[j], end="")
    print("")

In [13]:
def print_graph(graph):
  """
  Wypisuje na ekranie graf podany jako słownik (list) sąsiedztwa
  """
  for v in graph:
    print(v, ':', end="")
    for u in graph[v]:
      print(" ", u, end="")
    print("")


## Modyfikacje grafów

In [16]:
def add_vertex(graph, vertex):
  """
  Dodaje wierzchołek do grafu
  """
  if vertex not in graph:
    graph[vertex] = []

def add_arc(graph, arc):
  """
  Dodaje łuk (skierowany, podany jako para wierzchołków) do grafu
  """
  u, v = arc
  add_vertex(graph, u)
  add_vertex(graph, v)
  if v not in graph[u]:
    graph[u].append(v)

def add_edge(graph, edge):
  """
  Dodaje krawędź (podaną jako para wierzchołków) do grafu
  Rozpatrujemy grafy proste, nieskierowane
  """
  u, v = edge
  add_vertex(graph, u)
  add_vertex(graph, v)
  if u == v:
    raise ValueError("Pętla!!!")
  if v not in graph[u]:
    graph[u].append(v)
  if u not in graph[v]:
    graph[v].append(u)



# Testowanie funkcji

In [3]:
vertices = ['a', 'b', 'c', 'd']
matrix = np.array([[0,1,1,1],[1,0,0,0],[1,0,0,0],[1,0,0,0]])

In [4]:
print(vertices)

['a', 'b', 'c', 'd']


In [5]:
print(matrix)

[[0 1 1 1]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]]


In [6]:
print_matrix(vertices, matrix)

a :  b  c  d
b :  a
c :  a
d :  a


In [7]:
print_matrix(None, matrix)

1 :  2  3  4
2 :  1
3 :  1
4 :  1


In [8]:
print_matrix(['a','b'], matrix)

1 :  2  3  4
2 :  1
3 :  1
4 :  1


In [22]:
graph = {
    'a': ['b', 'c', 'd'],
    'b': ['a'],
    'c': ['a'],
    'd': ['a']
}

In [23]:
print(graph)

{'a': ['b', 'c', 'd'], 'b': ['a'], 'c': ['a'], 'd': ['a']}


In [24]:
print_graph(graph)

a :  b  c  d
b :  a
c :  a
d :  a


In [25]:
add_vertex(graph, 'e')

In [26]:
add_edge(graph, ('a', 'f'))

In [27]:
print_graph(graph)

a :  b  c  d  f
b :  a
c :  a
d :  a
e :
f :  a


In [28]:
add_edge(graph, ('e', 'f'))

In [29]:
add_edge(graph, ('f', 'f'))

ValueError: Pętla!!!

In [30]:
add_arc(graph, ('f', 'f'))

In [31]:
print_graph(graph)

a :  b  c  d  f
b :  a
c :  a
d :  a
e :  f
f :  a  e  f


In [35]:
add_arc(graph, ('b', 'f'))

In [36]:
print_graph(graph)

a :  b  c  d  f
b :  a  f
c :  a
d :  a
e :  f
f :  a  e  f


## Tworzenie grafów losowych $G(n,p)$

In [38]:
# dla powtarzalności
seed(2026)

In [39]:
#losujemy graf G(10, 1/3)
n = 10
p = 1/3
random_graph = {}
for i in range(1, n+1):
  add_vertex(random_graph, i)
  for j in range(1, i):
    if random() < p:
      add_edge(random_graph, (i, j))

In [40]:
print_graph(random_graph)

1 :  2
2 :  1  4  7  8  9  10
3 :  4  8
4 :  2  3
5 :  6  9
6 :  5
7 :  2
8 :  2  3
9 :  2  5  10
10 :  2  9
