<a href="https://colab.research.google.com/github/pgordin/OptDisc2026/blob/main/Grafy2a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importowanie pakietów

In [ ]:
import numpy as np
from random import random, seed

# Funkcje grafowe

In [ ]:
def print_matrix(vertices, matrix):
  """
  Wypisuje na ekranie graf podany jako macierz sąsiedztwa
  """
  n = len(matrix)
  if (vertices is None) or (len(vertices) != n):
    vv = range(1, n+1)
  else:
    vv = vertices
  for i in range(n):
    print(vv[i], ':', end='')
    for j in range(n):
      if (matrix[i][j]):
        print(" ", vv[j], end="")
    print("")

In [ ]:
def print_graph(graph):
  """
  Wypisuje na ekranie graf podany jako słownik (list) sąsiedztwa
  """
  for v in graph:
    print(v, ':', end="")
    for u in graph[v]:
      print(" ", u, end="")
    print("")


## Modyfikacje grafów

In [ ]:
def add_vertex(graph, vertex):
  """
  Dodaje wierzchołek do grafu
  """
  if vertex not in graph:
    graph[vertex] = []

def add_arc(graph, arc):
  """
  Dodaje łuk (skierowany, podany jako para wierzchołków) do grafu
  """
  u, v = arc
  add_vertex(graph, u)
  add_vertex(graph, v)
  if v not in graph[u]:
    graph[u].append(v)

def add_edge(graph, edge):
  """
  Dodaje krawędź (podaną jako para wierzchołków) do grafu
  Rozpatrujemy grafy proste, nieskierowane
  """
  u, v = edge
  add_vertex(graph, u)
  add_vertex(graph, v)
  if u == v:
    raise ValueError("Pętla!!!")
  if v not in graph[u]:
    graph[u].append(v)
  if u not in graph[v]:
    graph[v].append(u)



## Zapis i odczyt z plików

In [ ]:
def graph_from_edges(filename, directed=0):
  """
  Tworzy graf na podstawie pliku z krawędziami. Opis krawędzi to dwa słowa lub wierzchołka (jedno słowo).
  Nadmiarowe słowa są ignorowane.
  Zmienna filename zawiera pełną ścieżkę pliku
  """
  graph = {}
  with open(filename, 'r') as file: # otwarcie do odczytu
    for line in file:
      words = line.strip().split()
      if len(words) == 1:     # jedno słowo - opis wierzchołka
        add_vertex(graph, words[0])
      elif len(words) >= 2:   # co najmniej dwa słowa - opis krawędzi
        if directed:
          add_arc(graph, (words[0], words[1]))
        else:
          add_edge(graph, (words[0], words[1]))
  return graph

In [ ]:
def graph_to_neighbourlist(graph, filename):
  """
  Zapisuje graf podany jako słownik (list) sąsiedztwa do pliku (w formie listy sąsiedztwa).
  Zmienna filename zawiera pełną ścieżkę pliku
  """
  with open(filename, 'w') as file: # otwarcie do zapisu
    for v in graph:
      line = f"{v}:"
      for u in graph[v]:
        line += f" {u}"
      line += "\n"
      file.write(line)

# Testowanie funkcji

## Wczytywanie i zapis grafów

In [ ]:
%%writefile edges.txt
a b
a c
b d
c e
f

Writing edges.txt


In [ ]:
%cat edges.txt

a b
a c
b d
c e
f


In [ ]:
graph1 = graph_from_edges('edges.txt')

In [ ]:
print_graph(graph1)

a :  b  c
b :  a  d
c :  a  e
d :  b
e :  c
f :


In [ ]:
digraph1 = graph_from_edges('edges.txt', directed=1)
print_graph(digraph1)

a :  b  c
b :  d
c :  e
d :
e :
f :


In [ ]:
!wget https://raw.githubusercontent.com/pgordin/OptDisc2026/refs/heads/main/weighted0.txt

--2026-04-13 09:39:40--  https://raw.githubusercontent.com/pgordin/OptDisc2026/refs/heads/main/weighted0.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 114 [text/plain]
Saving to: ‘weighted0.txt’

weighted0.txt       100%[===================>]     114  --.-KB/s    in 0s      

2026-04-13 09:39:40 (2.46 MB/s) - ‘weighted0.txt’ saved [114/114]



In [ ]:
%cat weighted0.txt

A B 3
A E 10
B C 26
B D 12
C D 17
C F 13
C G 14
D E 7
D F 15
E F 8
E H 4
F G 9
F H 6
G H 16
G I 11


In [ ]:
graph2 = graph_from_edges('weighted0.txt')
print_graph(graph2)

A :  B  E
B :  A  C  D
E :  A  D  F  H
C :  B  D  F  G
D :  B  C  E  F
F :  C  D  E  G  H
G :  C  F  H  I
H :  E  F  G
I :  G


In [ ]:
graph_to_neighbourlist(graph2, 'graph2.txt')

In [ ]:
%cat graph2.txt

A: B E
B: A C D
E: A D F H
C: B D F G
D: B C E F
F: C D E G H
G: C F H I
H: E F G
I: G


## Pierwsze zajęcia

In [ ]:
vertices = ['a', 'b', 'c', 'd']
matrix = np.array([[0,1,1,1],[1,0,0,0],[1,0,0,0],[1,0,0,0]])

In [ ]:
print(vertices)

['a', 'b', 'c', 'd']


In [ ]:
print(matrix)

[[0 1 1 1]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]]


In [ ]:
print_matrix(vertices, matrix)

a :  b  c  d
b :  a
c :  a
d :  a


In [ ]:
print_matrix(None, matrix)

1 :  2  3  4
2 :  1
3 :  1
4 :  1


In [ ]:
print_matrix(['a','b'], matrix)

1 :  2  3  4
2 :  1
3 :  1
4 :  1


In [ ]:
graph = {
    'a': ['b', 'c', 'd'],
    'b': ['a'],
    'c': ['a'],
    'd': ['a']
}

In [ ]:
print(graph)

{'a': ['b', 'c', 'd'], 'b': ['a'], 'c': ['a'], 'd': ['a']}


In [ ]:
print_graph(graph)

a :  b  c  d
b :  a
c :  a
d :  a


In [ ]:
add_vertex(graph, 'e')

In [ ]:
add_edge(graph, ('a', 'f'))

In [ ]:
print_graph(graph)

a :  b  c  d  f
b :  a
c :  a
d :  a
e :
f :  a


In [ ]:
add_edge(graph, ('e', 'f'))

In [ ]:
add_edge(graph, ('f', 'f'))

ValueError: Pętla!!!

In [ ]:
add_arc(graph, ('f', 'f'))

In [ ]:
print_graph(graph)

a :  b  c  d  f
b :  a
c :  a
d :  a
e :  f
f :  a  e  f


In [ ]:
add_arc(graph, ('b', 'f'))

In [ ]:
print_graph(graph)

a :  b  c  d  f
b :  a  f
c :  a
d :  a
e :  f
f :  a  e  f


## Tworzenie grafów losowych $G(n,p)$

In [ ]:
# dla powtarzalności
seed(2026)

In [ ]:
#losujemy graf G(10, 1/3)
n = 10
p = 1/3
random_graph = {}
for i in range(1, n+1):
  add_vertex(random_graph, i)
  for j in range(1, i):
    if random() < p:
      add_edge(random_graph, (i, j))

In [ ]:
print_graph(random_graph)

1 :  2
2 :  1  4  7  8  9  10
3 :  4  8
4 :  2  3
5 :  6  9
6 :  5
7 :  2
8 :  2  3
9 :  2  5  10
10 :  2  9
