<a href="https://colab.research.google.com/github/pgordin/OptDisc2026/blob/main/Grafy1b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from random import random, seed

# Funkcje grafowe

In [2]:
def print_matrix(vertices, matrix):
  """
  Wypisuje na ekranie graf, podany jako macierz sąsiedztwa
  """
  n = len(matrix)
  if (vertices is None) or (len(vertices) != n):
    vv = range(1, n+1)
  else:
    vv = vertices
  for i in range(n):
    print(vv[i], ": ", end="", sep="")
    for j in range(n):
      if matrix[i, j]:
        print(" ", vv[j], sep="", end="")
    print("")

In [15]:
def print_graph(graph):
  """
  Wypisuje graf w postaci słownika/listy sąsiedztwa.
  """
  for v in graph:
    print(v, ":", sep="", end="")
    for u in graph[v]:
      print(" ", u, sep="", end="")
    print("")

## Modyfikacje grafów

In [27]:
def add_vertex(graph, vertex):
  """
  Dodaje wierzchołek do grafu.
  """
  if vertex not in graph:
    graph[vertex] = []

def add_arc(graph, arc):
  """
  Dodaje łuk (skierowany, podany jako para wierzchołków) do grafu (prostego).
  """
  u, v = arc
  add_vertex(graph, u)
  add_vertex(graph, v)
  if v not in graph[u]:
    graph[u].append(v)


def add_edge(graph, edge):
  """
  Dodaje krawędź (nieskierowany, podany jako para wierzchołków) do grafu (prostego).
  """
  u, v = edge
  add_vertex(graph, u)
  add_vertex(graph, v)
  if u == v:
    raise ValueError("Graf nieskierowany nie może mieć pętli!")
  if v not in graph[u]:
    graph[u].append(v)
  if u not in graph[v]:
    graph[v].append(u)

# Testowanie funkcji

In [3]:
vertices = ['a', 'b', 'c', 'd', 'e']
matrix = np.array([[0, 1, 1, 0, 0],
                   [1, 0, 0, 1, 0],
                   [1, 0, 0, 0, 1],
                   [0, 1, 0, 0, 1],
                   [0, 0, 1, 1, 0]])

In [4]:
print(vertices)

['a', 'b', 'c', 'd', 'e']


In [5]:
print(matrix)

[[0 1 1 0 0]
 [1 0 0 1 0]
 [1 0 0 0 1]
 [0 1 0 0 1]
 [0 0 1 1 0]]


In [6]:
print_matrix(vertices, matrix)

a:  b c
b:  a d
c:  a e
d:  b e
e:  c d


In [9]:
print_matrix(None , matrix)

1:  2 3
2:  1 4
3:  1 5
4:  2 5
5:  3 4


In [10]:
print_matrix(['a', 'b'] , matrix)

1:  2 3
2:  1 4
3:  1 5
4:  2 5
5:  3 4


In [28]:
graph = {
  'a': ['b', 'c'],
  'b': ['a', 'd'],
  'c': ['a', 'e'],
  'd': ['b', 'e'],
  'e': ['c', 'd']
}

In [29]:
print(graph)

{'a': ['b', 'c'], 'b': ['a', 'd'], 'c': ['a', 'e'], 'd': ['b', 'e'], 'e': ['c', 'd']}


In [30]:
print_graph(graph)

a: b c
b: a d
c: a e
d: b e
e: c d


In [31]:
add_vertex(graph, 'f')

In [32]:
print_graph(graph)

a: b c
b: a d
c: a e
d: b e
e: c d
f:


In [33]:
add_arc(graph, ('f', 'g'))

In [34]:
print_graph(graph)

a: b c
b: a d
c: a e
d: b e
e: c d
f: g
g:


In [35]:
add_edge(graph, ('f', 'g'))

In [36]:
print_graph(graph)

a: b c
b: a d
c: a e
d: b e
e: c d
f: g
g: f


In [37]:
add_edge(graph, ('f', 'f'))

ValueError: Graf nieskierowany nie może mieć pętli!

In [38]:
add_arc(graph, ('f', 'f'))

In [39]:
print_graph(graph)

a: b c
b: a d
c: a e
d: b e
e: c d
f: g f
g: f


## Generowanie grafów losowych w modeli $G(n,p)$

In [47]:
# dla powtarzalności
seed(2026)

In [48]:
# losujemy graf G(10, 1/3)
n = 10
p = 1/3
random_graph = {}
for i in range(1, n+1):
  add_vertex(random_graph, i)
  for j in range(1, i):
    if random() < p:
      add_edge(random_graph, (i, j))

In [49]:
print_graph(random_graph)

1: 2
2: 1 4 7 8 9 10
3: 4 8
4: 2 3
5: 6 9
6: 5
7: 2
8: 2 3
9: 2 5 10
10: 2 9
