<a href="https://colab.research.google.com/github/pgordin/OptDisc2026/blob/main/Grafy2b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from random import random, seed

# Funkcje grafowe

In [ ]:
def print_matrix(vertices, matrix):
  """
  Wypisuje na ekranie graf, podany jako macierz sąsiedztwa
  """
  n = len(matrix)
  if (vertices is None) or (len(vertices) != n):
    vv = range(1, n+1)
  else:
    vv = vertices
  for i in range(n):
    print(vv[i], ": ", end="", sep="")
    for j in range(n):
      if matrix[i, j]:
        print(" ", vv[j], sep="", end="")
    print("")

In [ ]:
def print_graph(graph):
  """
  Wypisuje graf w postaci słownika/listy sąsiedztwa.
  """
  for v in graph:
    print(v, ":", sep="", end="")
    for u in graph[v]:
      print(" ", u, sep="", end="")
    print("")

## Modyfikacje grafów

In [ ]:
def add_vertex(graph, vertex):
  """
  Dodaje wierzchołek do grafu.
  """
  if vertex not in graph:
    graph[vertex] = []

def add_arc(graph, arc):
  """
  Dodaje łuk (skierowany, podany jako para wierzchołków) do grafu (prostego).
  """
  u, v = arc
  add_vertex(graph, u)
  add_vertex(graph, v)
  if v not in graph[u]:
    graph[u].append(v)


def add_edge(graph, edge):
  """
  Dodaje krawędź (nieskierowany, podany jako para wierzchołków) do grafu (prostego).
  """
  u, v = edge
  add_vertex(graph, u)
  add_vertex(graph, v)
  if u == v:
    raise ValueError("Graf nieskierowany nie może mieć pętli!")
  if v not in graph[u]:
    graph[u].append(v)
  if u not in graph[v]:
    graph[v].append(u)

## Wczytywanie i zapis grafów do/z pliku

In [ ]:
def graph_from_edges(filename, directed=0):
  """
  Wczytuje graf z pliku, gdzie jest podany jako opis krawędzi:
  - jedno słowo - wierzchołek izolowany
  - dwa słowa - krawędź nieskierowana (lub łuk).
  filename to pełna ścieżka dostępu do pliku.
  """
  graph = {}
  with open(filename, 'r') as file:   # otwarcie pliku do odczytu
    for line in file:
      words = line.strip().split()
      if len(words) == 1:             # jedno słowo - izolowany wierzchołek
        add_vertex(graph, words[0])
      elif len(words) >= 2:           # conajmniej dwa słowa - opis krawędzi lub łuku
        if directed:
          add_arc(graph, (words[0], words[1]))
        else:
          add_edge(graph, (words[0], words[1]))
  return graph

In [ ]:
def graph_to_neighbourlist(graph, filename):
  """
  Zapisuje graf w postaci listy sąsiedztwa do pliku.
  """
  with open(filename, 'w') as file:
    for v in graph:
      line = f"{v}:"
      for u in graph[v]:
        line += f" {u}"
      line += "\n"
      file.write(line)

# Testowanie funkcji

## Wczytywanie i zapis grafów z plików

In [ ]:
%cat graf0.txt

a b
a c
d


In [ ]:
graph0 = graph_from_edges('graf0.txt')
print_graph(graph0)

a: b c
b: a
c: a
d:


In [ ]:
%%writefile graf1.txt
b c
a d
a e
b e
c d

Writing graf1.txt


In [ ]:
digraph1 = graph_from_edges('graf1.txt', directed=1)
print_graph(digraph1)

b: c e
c: d
a: d e
d:
e:


In [ ]:
!wget https://raw.githubusercontent.com/pgordin/OptDisc2026/refs/heads/main/weighted0.txt

--2026-04-13 15:23:48--  https://raw.githubusercontent.com/pgordin/OptDisc2026/refs/heads/main/weighted0.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 114 [text/plain]
Saving to: ‘weighted0.txt’

weighted0.txt       100%[===================>]     114  --.-KB/s    in 0s      

2026-04-13 15:23:48 (1.37 MB/s) - ‘weighted0.txt’ saved [114/114]



In [ ]:
%cat weighted0.txt

A B 3
A E 10
B C 26
B D 12
C D 17
C F 13
C G 14
D E 7
D F 15
E F 8
E H 4
F G 9
F H 6
G H 16
G I 11


In [ ]:
graph2 = graph_from_edges('weighted0.txt')
print_graph(graph2)

A: B E
B: A C D
E: A D F H
C: B D F G
D: B C E F
F: C D E G H
G: C F H I
H: E F G
I: G


In [ ]:
graph_to_neighbourlist(graph2, 'graph2.txt')

In [ ]:
%cat graph2.txt

A: B E
B: A C D
E: A D F H
C: B D F G
D: B C E F
F: C D E G H
G: C F H I
H: E F G
I: G


## Pierwsze zajęcia

In [ ]:
vertices = ['a', 'b', 'c', 'd', 'e']
matrix = np.array([[0, 1, 1, 0, 0],
                   [1, 0, 0, 1, 0],
                   [1, 0, 0, 0, 1],
                   [0, 1, 0, 0, 1],
                   [0, 0, 1, 1, 0]])

In [ ]:
print(vertices)

['a', 'b', 'c', 'd', 'e']


In [ ]:
print(matrix)

[[0 1 1 0 0]
 [1 0 0 1 0]
 [1 0 0 0 1]
 [0 1 0 0 1]
 [0 0 1 1 0]]


In [ ]:
print_matrix(vertices, matrix)

a:  b c
b:  a d
c:  a e
d:  b e
e:  c d


In [ ]:
print_matrix(None , matrix)

1:  2 3
2:  1 4
3:  1 5
4:  2 5
5:  3 4


In [ ]:
print_matrix(['a', 'b'] , matrix)

1:  2 3
2:  1 4
3:  1 5
4:  2 5
5:  3 4


In [ ]:
graph = {
  'a': ['b', 'c'],
  'b': ['a', 'd'],
  'c': ['a', 'e'],
  'd': ['b', 'e'],
  'e': ['c', 'd']
}

In [ ]:
print(graph)

{'a': ['b', 'c'], 'b': ['a', 'd'], 'c': ['a', 'e'], 'd': ['b', 'e'], 'e': ['c', 'd']}


In [ ]:
print_graph(graph)

a: b c
b: a d
c: a e
d: b e
e: c d


In [ ]:
add_vertex(graph, 'f')

In [ ]:
print_graph(graph)

a: b c
b: a d
c: a e
d: b e
e: c d
f:


In [ ]:
add_arc(graph, ('f', 'g'))

In [ ]:
print_graph(graph)

a: b c
b: a d
c: a e
d: b e
e: c d
f: g
g:


In [ ]:
add_edge(graph, ('f', 'g'))

In [ ]:
print_graph(graph)

a: b c
b: a d
c: a e
d: b e
e: c d
f: g
g: f


In [ ]:
add_edge(graph, ('f', 'f'))

ValueError: Graf nieskierowany nie może mieć pętli!

In [ ]:
add_arc(graph, ('f', 'f'))

In [ ]:
print_graph(graph)

a: b c
b: a d
c: a e
d: b e
e: c d
f: g f
g: f


## Generowanie grafów losowych w modeli $G(n,p)$

In [ ]:
# dla powtarzalności
seed(2026)

In [ ]:
# losujemy graf G(10, 1/3)
n = 10
p = 1/3
random_graph = {}
for i in range(1, n+1):
  add_vertex(random_graph, i)
  for j in range(1, i):
    if random() < p:
      add_edge(random_graph, (i, j))

In [ ]:
print_graph(random_graph)

1: 2
2: 1 4 7 8 9 10
3: 4 8
4: 2 3
5: 6 9
6: 5
7: 2
8: 2 3
9: 2 5 10
10: 2 9
