<a href="https://colab.research.google.com/github/pgordin/OptDisc2026/blob/main/Zadanie_1_NK_DD_(tworzenie_i_modyfikacje_graf%C3%B3w).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#zadanie 1
def print_matrix(vertices, matrix):
  n = len(matrix)
  if (vertices is None) or (len(vertices) != n):
    vv = range(1, n+1)
  else:
    vv = vertices
  for i in range(n):
    print(vv[i], ": ", end="", sep="")
    for j in range(n):
      if matrix[i, j]:
        print(" ", vv[j], sep="", end="")
    print("")

import random
import numpy as np

def random_graph(n, p):
    matrix = np.zeros((n, n), dtype=int)

    for i in range(n):
        for j in range(i + 1, n):
            if random.random() < p:
                matrix[i, j] = 1
                matrix[j, i] = 1

    return matrix

G = random_graph(8, 0.2)
print_matrix(None, G)

1:  4
2: 
3:  7 8
4:  1 6 7
5: 
6:  4
7:  3 4 8
8:  3 7


In [11]:
#zadanie 2
import numpy as np

def graph_to_matrix(graph):
    vertices = sorted(graph.keys())
    n = len(vertices)

    index = {v: i for i, v in enumerate(vertices)}

    matrix = np.zeros((n, n), dtype=int)

    for v in graph:
        for u in graph[v]:
            i = index[v]
            j = index[u]
            matrix[i, j] = 1

    return vertices, matrix

graph = {
    1: [2, 4],
    2: [1],
    3: [],
    4: [1]
}

vertices, matrix = graph_to_matrix(graph)

print(matrix)

print_matrix(vertices, matrix)

[[0 1 0 1]
 [1 0 0 0]
 [0 0 0 0]
 [1 0 0 0]]
1:  2 4
2:  1
3: 
4:  1


In [16]:
#zadanie 3
def print_graph(graph):
  for v in graph:
    print(v, ":", sep="", end="")
    for u in graph[v]:
      print(" ", u, sep="", end="")
    print("")

def matrix_to_graph(vertices, matrix):
    graph = {}

    n = len(vertices)

    for i in range(n):
        v = vertices[i]
        graph[v] = []

        for j in range(n):
            if matrix[i, j] == 1:
                graph[v].append(vertices[j])

    return graph

graph2 = matrix_to_graph(vertices, matrix)
print_graph(graph2)

1: 2 4
2: 1
3:
4: 1


In [19]:
#zadanie 4
def cycle(n):
    graph = {i: [] for i in range(1, n+1)}

    for i in range(1, n):
        graph[i].append(i+1)
        graph[i+1].append(i)

    #zamknięcie cyklu
    graph[n].append(1)
    graph[1].append(n)

    return graph

G = cycle(8)
print_graph(G)

1: 2 8
2: 1 3
3: 2 4
4: 3 5
5: 4 6
6: 5 7
7: 6 8
8: 7 1
